### ISSUE TITLE
能不能发一个安装教程啊？

### ISSUE THREAD

**Issue by tokpig** [ailuoku6/gy_nav#1]
我是小白，教教我行不行？
QQ群也弄一个嘛
v2过来的

**Comment by jiqing112** [comment]
qq群倒不至于了，文档多写点就行了吧。
而且注册登录这些操作，怎么在自己的主机上用

**Comment by tokpig** [comment]
> QQ群倒不至于了，文档多写点就行了吧。
> 而且注册登录这些操作，怎么在自己的主机上用

安装好了，就是不能登陆，这个也没有数据库，不知道咋对接哎

**Comment by ailuoku6** [comment]
> > QQ群倒不至于了，文档多写点就行了吧。
> > 而且注册登录这些操作，怎么在自己的主机上用
> 
> 安装好了，就是不能登陆，这个也没有数据库，不知道咋对接哎

后端代码不贴了，看这些代码自己写个后端就行
